language: php

matrix:
  include:
    - os: linux
      dist: precise
      php: 5.3
    - os: linux
      dist: trusty
      php: 5.4
    - os: linux
      dist: trusty
      php: 5.5
    - os: linux
      dist: trusty
      php: 5.6
    - os: linux
      dist: trusty
      php: 7.0
    - os: linux
      dist: trusty
      php: 7.1

before_script:
  - 'composer install --dev --prefer-source'

script: php test/test.php

after_script:
  - if [ $(phpenv version-name) = "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) = "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
